// Visual catalogue only. Purchasing and ownership belong to the server.
export const COLLECTIBLE_EDITIONS = {
  holo: { name: "Holographic", series: "heritage", serial: "01" },
  carbon: { name: "Carbon", series: "heritage", serial: "02" },
  prisma: { name: "Prism", series: "heritage", serial: "03" },
  aurora: { name: "Racing Green", series: "heritage", serial: "04" },
  solar: { name: "Heritage", series: "heritage", serial: "05" },
  glacier: { name: "Silver", series: "heritage", serial: "06" },
  void: { name: "Black Edition", series: "heritage", serial: "07" },
  rose: { name: "Copper", series: "heritage", serial: "08" },
  circuit: { name: "Telemetry", series: "heritage", serial: "09" },
  "spectrum-holo": { name: "Liquid Holo", series: "spectrum", material: "holo", serial: "01" },
  "spectrum-carbon": { name: "Carbon Ember", series: "spectrum", material: "carbon", serial: "02" },
  "spectrum-prisma": { name: "Prisma Nova", series: "spectrum", material: "prisma", serial: "03" },
  "spectrum-aurora": { name: "Aurora", series: "spectrum", material: "aurora", serial: "04" },
  "spectrum-solar": { name: "Solar Flare", series: "spectrum", material: "solar", serial: "05" },
  "spectrum-glacier": { name: "Glacier", series: "spectrum", material: "glacier", serial: "06" },
  "spectrum-void": { name: "Void", series: "spectrum", material: "void", serial: "07" },
  "spectrum-rose": { name: "Rose Chrome", series: "spectrum", material: "rose", serial: "08" },
  "spectrum-circuit": { name: "Circuit", series: "spectrum", material: "circuit", serial: "09" },
  "velocity-scarlet": { name: "Scarlet", series: "velocity", serial: "01" },
  "velocity-electric": { name: "Electric", series: "velocity", serial: "02" },
  "velocity-arctic": { name: "Arctic", series: "velocity", serial: "03" },
  "signature-gold": { name: "Gold", series: "signature", serial: "01" },
  "signature-platinum": { name: "Platinum", series: "signature", serial: "02" },
  "signature-amethyst": { name: "Amethyst", series: "signature", serial: "03" },
  "concept-liquid": { name: "Liquid Chrome", series: "concepts", serial: "01" },
  "concept-race": { name: "Race Cut", series: "concepts", serial: "02" },
  "concept-blue": { name: "Studio Blue", series: "concepts", serial: "03" },
  "concept-pearl": { name: "Black Pearl", series: "concepts", serial: "04" },
};

export const CARD_COLLECTIONS = [
  { key: "concepts", name: "Concepts" },
  { key: "spectrum", name: "Spectrum" },
  { key: "heritage", name: "Heritage" },
  { key: "velocity", name: "Velocity" },
  { key: "signature", name: "Signature" },
];
