// ---------------------------------------------------------------------------
// Per-race photo gallery: the shots from a race night (screenshots, podium
// pictures, the crash everybody talked about), uploaded by an admin and shown
// on the round's page as a carousel.
//
// Stored as a Setting blob keyed by the race id, the same pattern as
// raceInfo.js / trackInfo.js: no migration to deploy, and the files themselves
// live on disk under UPLOADS_DIR/races/ like every other admin upload.
//
// The blob holds the FILE NAME, not the URL. The URL is built on the way out,
// so moving where uploads are served from stays a one-line change instead of a
// rewrite of every stored row.
// ---------------------------------------------------------------------------

const KEY_PREFIX = "race_photos_";
// A race night's worth of pictures. High enough that nobody has to choose,
// low enough that one round can't quietly fill the disk.
export const MAX_PHOTOS = 40;
const MAX_CAPTION = 140;
// Only what a browser reliably renders inline. Kept in step with the admin
// route's accepted mime types.
const ALLOWED_EXT = new Set([".png", ".jpg", ".jpeg", ".webp", ".gif"]);

export const racePhotoUrl = (file) => `/api/uploads/races/${file}`;

// A stored file name is generated by us (see the admin route), never by the
// uploader. This guards the READ path anyway: a hand-edited blob must not be
// able to point the gallery at ../../dev.db.
function cleanFile(name) {
  const s = String(name || "");
  if (!/^[A-Za-z0-9._-]+$/.test(s) || s.includes("..")) return null;
  const dot = s.lastIndexOf(".");
  if (dot < 1) return null;
  return ALLOWED_EXT.has(s.slice(dot).toLowerCase()) ? s : null;
}

export function sanitizeRacePhotos(input) {
  const list = Array.isArray(input) ? input : Array.isArray(input?.photos) ? input.photos : [];
  const out = [];
  const seen = new Set();
  for (const p of list) {
    const file = cleanFile(p?.file);
    if (!file || seen.has(file)) continue;
    seen.add(file);
    out.push({
      // The id is what the admin's reorder/delete calls address a row by; it
      // survives a caption edit, which the file name would too, but the file
      // name is an implementation detail the editor shouldn't have to carry.
      id: String(p?.id || file).slice(0, 64),
      file,
      caption: typeof p?.caption === "string" ? p.caption.slice(0, MAX_CAPTION).trim() : "",
    });
    if (out.length >= MAX_PHOTOS) break;
  }
  return out;
}

// The shape every reader gets: ready to render, newest edit order preserved.
export function withUrls(photos) {
  return photos.map((p) => ({ id: p.id, url: racePhotoUrl(p.file), caption: p.caption }));
}

export async function readRacePhotos(prisma, raceId) {
  if (!raceId) return [];
  try {
    const row = await prisma.setting.findUnique({ where: { key: KEY_PREFIX + raceId } });
    if (!row?.value) return [];
    return sanitizeRacePhotos(JSON.parse(row.value));
  } catch {
    return [];
  }
}

export async function writeRacePhotos(prisma, raceId, photos) {
  const clean = sanitizeRacePhotos(photos);
  const key = KEY_PREFIX + raceId;
  // An empty gallery is the absence of a row, not a row holding "[]": it keeps
  // the Setting table honest and makes the count query below a plain lookup.
  if (!clean.length) {
    await prisma.setting.deleteMany({ where: { key } });
    return clean;
  }
  const json = JSON.stringify(clean);
  await prisma.setting.upsert({ where: { key }, create: { key, value: json }, update: { value: json } });
  return clean;
}

// raceId -> how many photos it has, for the lists (the admin's race picker and
// the public calendar's little camera mark). One query for the whole page
// rather than one per round.
export async function readPhotoCounts(prisma, raceIds) {
  const ids = [...new Set((raceIds || []).filter(Boolean))];
  const out = new Map();
  if (!ids.length) return out;
  try {
    const rows = await prisma.setting.findMany({
      where: { key: { in: ids.map((id) => KEY_PREFIX + id) } },
      select: { key: true, value: true },
    });
    for (const r of rows) {
      const id = r.key.slice(KEY_PREFIX.length);
      let n = 0;
      try {
        n = sanitizeRacePhotos(JSON.parse(r.value)).length;
      } catch {
        n = 0;
      }
      if (n) out.set(id, n);
    }
  } catch {
    /* a missing Setting table is not worth failing a calendar over */
  }
  return out;
}
