// ---------------------------------------------------------------------------
// Racing series (the level above Season). One deployment can host several
// independent championships (Friday F1, Sunday GT, ...): each series has its
// own seasons/teams/drivers/races/standings, while Discord login, members,
// downloads and the bot stay global. Exactly one series is `isActive` (the
// primary one "/" redirects to); `slug` is the URL identity (/s/<slug>/…) and
// stays stable after creation — only `name` is renamable.
//
// Like MemberAccount/Download/PersonLink, managed via raw SQL (the running dev
// server locks the generated Prisma client on Windows). Keep in sync with the
// Series model in prisma/schema.prisma.
// ---------------------------------------------------------------------------
import { randomUUID } from "crypto";
import { refreshArchiveIndex } from "./resultsArchive.js";

// Shape a raw row for callers: numbers/booleans normalised.
function shapeSeries(r) {
  if (!r) return null;
  return {
    id: r.id,
    name: r.name,
    slug: r.slug,
    game: r.game || null,
    description: r.description || null,
    order: Number(r.order ?? 0),
    isActive: !!Number(r.isActive ?? 0),
    isPublic: r.isPublic == null ? true : !!Number(r.isPublic),
    accentColor: r.accentColor || null,
    logoDarkUrl: r.logoDarkUrl || null,
    shareImageUrl: r.shareImageUrl || null,
    shareImages: parseShareImages(r.shareImages),
    shareTexts: parseShareTexts(r.shareTexts),
    createdAt: r.createdAt,
  };
}

// Write the series' uploaded dark-mode logo URL (or null to clear it, back to
// the shared default logo-dark.png). Not routed through dbUpdateSeries's
// generic patch — the URL is server-generated by the upload endpoint, never
// admin-typed, so it doesn't need the validation dbUpdateSeries would apply
// to a user-editable field.
export async function writeSeriesLogo(prisma, id, url) {
  await prisma.$executeRawUnsafe(`UPDATE "Series" SET "logoDarkUrl" = ? WHERE "id" = ?`, url, id);
}

// The pages of a series that can carry a link-preview picture of their own,
// on top of the series-wide one (shareImageUrl). Keys are the section names
// in /s/<slug>/<section> (aliases folded, see lib/pageMeta.js), plus "home"
// for the landing page. Labels are what the Series tab shows.
export const SHARE_PAGES = {
  home: "Home page",
  attendance: "Sign-ups & attendance",
  drivers: "Driver standings",
  constructors: "Constructor standings",
  races: "Results & calendar",
  transfers: "Transfers",
  records: "Records",
  live: "Live timing",
};

// Series.shareImages: a JSON object { <page>: <url> }. Anything unreadable, or
// any key that is not a known page, is dropped rather than trusted.
function parseShareImages(raw) {
  let obj = {};
  try {
    obj = raw ? JSON.parse(raw) : {};
  } catch {
    obj = {};
  }
  const out = {};
  for (const [k, v] of Object.entries(obj || {})) {
    if (SHARE_PAGES[k] && typeof v === "string" && v) out[k] = v;
  }
  return out;
}

// Write the series' uploaded link-preview picture (og:image) URL, or null to
// clear it. Server-generated, like the logo. Without a page it is the
// series-wide picture (back to the shared og-image.jpg when cleared); with one
// it is that page's own (back to the series-wide picture when cleared).
export async function writeSeriesShareImage(prisma, id, url, page = null) {
  if (!page) {
    await prisma.$executeRawUnsafe(`UPDATE "Series" SET "shareImageUrl" = ? WHERE "id" = ?`, url, id);
    return;
  }
  const rows = await prisma.$queryRawUnsafe(`SELECT "shareImages" FROM "Series" WHERE "id" = ?`, id);
  const map = parseShareImages(rows?.[0]?.shareImages);
  if (url) map[page] = url;
  else delete map[page];
  const json = Object.keys(map).length ? JSON.stringify(map) : null;
  await prisma.$executeRawUnsafe(`UPDATE "Series" SET "shareImages" = ? WHERE "id" = ?`, json, id);
}

// Series.shareTexts: JSON { <page>: { title?, description? } }, the admin's
// own wording for a page's link preview (og:/twitter: tags only; the page
// title and search snippet keep theirs, lib/pageMeta.js applyShareText).
// Unknown pages, non-strings and blanks are dropped.
export const SHARE_TITLE_MAX = 200;
export const SHARE_DESCRIPTION_MAX = 400;
function parseShareTexts(raw) {
  let obj = {};
  try {
    obj = raw ? JSON.parse(raw) : {};
  } catch {
    obj = {};
  }
  const out = {};
  for (const [k, v] of Object.entries(obj || {})) {
    if (!SHARE_PAGES[k] || !v || typeof v !== "object") continue;
    const entry = {};
    if (typeof v.title === "string" && v.title.trim()) entry.title = v.title.trim();
    if (typeof v.description === "string" && v.description.trim()) entry.description = v.description.trim();
    if (Object.keys(entry).length) out[k] = entry;
  }
  return out;
}

// Validates an admin's { title, description } for a page. Blank (or missing)
// means "use the automatic one". Returns { ok, value } or { ok: false, error }.
export function parseShareText(body) {
  const title = String(body?.title ?? "").replace(/\s+/g, " ").trim();
  const description = String(body?.description ?? "").replace(/\s+/g, " ").trim();
  if (title.length > SHARE_TITLE_MAX) return { ok: false, error: `Title is longer than ${SHARE_TITLE_MAX} characters` };
  if (description.length > SHARE_DESCRIPTION_MAX) {
    return { ok: false, error: `Description is longer than ${SHARE_DESCRIPTION_MAX} characters` };
  }
  return { ok: true, value: { ...(title ? { title } : {}), ...(description ? { description } : {}) } };
}

// Write one page's link-preview wording (an empty object clears it).
export async function writeSeriesShareText(prisma, id, page, value) {
  const rows = await prisma.$queryRawUnsafe(`SELECT "shareTexts" FROM "Series" WHERE "id" = ?`, id);
  const map = parseShareTexts(rows?.[0]?.shareTexts);
  if (value && Object.keys(value).length) map[page] = value;
  else delete map[page];
  const json = Object.keys(map).length ? JSON.stringify(map) : null;
  await prisma.$executeRawUnsafe(`UPDATE "Series" SET "shareTexts" = ? WHERE "id" = ?`, json, id);
}

// Admin-picked accent colour: a plain 6-digit hex like "#6de0fc", or "" /
// null / undefined to clear it (back to the default NABS pink). Anything else
// is rejected — this rides straight into inline CSS custom properties on the
// client, so it must never carry anything but a colour.
const HEX_COLOR_RE = /^#[0-9a-f]{6}$/i;
export function parseAccentColor(v) {
  if (v === undefined) return { ok: true, skip: true };
  if (v === null || v === "") return { ok: true, value: null };
  const s = String(v).trim();
  if (!HEX_COLOR_RE.test(s)) {
    return { ok: false, error: "accentColor must be a 6-digit hex colour like #6de0fc, or blank" };
  }
  return { ok: true, value: s.toLowerCase() };
}

// URL-safe slug from a series name ("Sunday GT Masters" -> "sunday-gt-masters").
export function slugifySeries(name) {
  return String(name || "")
    .toLowerCase()
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

// All series, switcher order. includePrivate=false hides unpublished ones.
export async function dbListSeries(prisma, { includePrivate = false } = {}) {
  let rows = [];
  try {
    rows = await prisma.$queryRawUnsafe(
      `SELECT * FROM "Series" ORDER BY "order" ASC, "createdAt" ASC`
    );
  } catch {
    // Table missing (fresh checkout before ensureAppSchema): no series yet.
    return [];
  }
  const all = rows.map(shapeSeries);
  return includePrivate ? all : all.filter((s) => s.isPublic || s.isActive);
}

// The primary series (isActive), with sensible fallbacks so a broken flag can
// never blank the whole site: first public series by order, else just the first.
export async function getActiveSeries(prisma) {
  const all = await dbListSeries(prisma, { includePrivate: true });
  return all.find((s) => s.isActive) || all.find((s) => s.isPublic) || all[0] || null;
}

// Resolve an optional ?series=<slug> to a series row. No slug -> the active
// series. Unknown slug -> null. A PRIVATE series resolves to null for public
// callers so its data can't be reached by a crafted URL; admins see it.
export async function resolveSeries(prisma, slug, { includePrivate = false } = {}) {
  if (slug === undefined || slug === null || slug === "") {
    return getActiveSeries(prisma);
  }
  const all = await dbListSeries(prisma, { includePrivate: true });
  const s = all.find((x) => x.slug === String(slug)) || null;
  if (!s) return null;
  if (!includePrivate && !s.isPublic && !s.isActive) return null;
  return s;
}

export async function getSeriesById(prisma, id) {
  const all = await dbListSeries(prisma, { includePrivate: true });
  return all.find((s) => s.id === id) || null;
}

// Create a series. The slug is derived from the name (or taken explicitly),
// uniquified with a numeric suffix, and FROZEN afterwards.
export async function dbCreateSeries(prisma, { name, slug, game, description, accentColor }) {
  const base = slugifySeries(slug || name) || "series";
  const all = await dbListSeries(prisma, { includePrivate: true });
  const taken = new Set(all.map((s) => s.slug));
  let finalSlug = base;
  for (let i = 2; taken.has(finalSlug); i++) finalSlug = `${base}-${i}`;
  const id = randomUUID();
  const order = all.length ? Math.max(...all.map((s) => s.order)) + 1 : 0;
  const color = parseAccentColor(accentColor);
  if (!color.ok) throw Object.assign(new Error(color.error), { status: 400 });
  // New series start PRIVATE (like new seasons): built up quietly, published
  // when ready. The first series ever is created public by the backfill.
  await prisma.$executeRawUnsafe(
    `INSERT INTO "Series" ("id","name","slug","game","description","order","isActive","isPublic","accentColor")
     VALUES (?, ?, ?, ?, ?, ?, 0, 0, ?)`,
    id,
    String(name).trim(),
    finalSlug,
    game ? String(game).trim() : null,
    description ? String(description).trim() : null,
    order,
    color.skip ? null : color.value
  );
  return getSeriesById(prisma, id);
}

// Update name/game/description/order/isPublic. The slug is deliberately NOT
// updatable — it's the URL identity shared links depend on.
export async function dbUpdateSeries(prisma, id, patch) {
  const sets = [];
  const vals = [];
  if (patch.name !== undefined) {
    sets.push(`"name" = ?`);
    vals.push(String(patch.name).trim());
  }
  if (patch.game !== undefined) {
    sets.push(`"game" = ?`);
    vals.push(patch.game ? String(patch.game).trim() : null);
  }
  if (patch.description !== undefined) {
    sets.push(`"description" = ?`);
    vals.push(patch.description ? String(patch.description).trim() : null);
  }
  if (patch.order !== undefined) {
    sets.push(`"order" = ?`);
    vals.push(Number(patch.order) || 0);
  }
  if (patch.isPublic !== undefined) {
    sets.push(`"isPublic" = ?`);
    vals.push(patch.isPublic ? 1 : 0);
  }
  if (patch.accentColor !== undefined) {
    const color = parseAccentColor(patch.accentColor);
    if (!color.ok) throw Object.assign(new Error(color.error), { status: 400 });
    sets.push(`"accentColor" = ?`);
    vals.push(color.value);
  }
  if (sets.length) {
    await prisma.$executeRawUnsafe(`UPDATE "Series" SET ${sets.join(", ")} WHERE "id" = ?`, ...vals, id);
  }
  return getSeriesById(prisma, id);
}

// Make this the primary series ("/" redirects here). Exactly one is active;
// an active series is forced public — being the site default is publishing.
export async function dbActivateSeries(prisma, id) {
  await prisma.$executeRawUnsafe(`UPDATE "Series" SET "isActive" = 0`);
  await prisma.$executeRawUnsafe(`UPDATE "Series" SET "isActive" = 1, "isPublic" = 1 WHERE "id" = ?`, id);
}

export async function dbDeleteSeries(prisma, id) {
  await prisma.$executeRawUnsafe(`DELETE FROM "Series" WHERE "id" = ?`, id);
}

// The seasons of one series: [{ id, number }]. Raw read because seriesId is a
// raw-SQL column the generated client may not know yet.
export async function seasonIdsOfSeries(prisma, seriesId) {
  try {
    const rows = await prisma.$queryRawUnsafe(
      `SELECT "id", "number" FROM "Season" WHERE "seriesId" = ? ORDER BY "number" ASC`,
      seriesId
    );
    return rows.map((r) => ({ id: r.id, number: Number(r.number) }));
  } catch {
    return [];
  }
}

// Map seasonId -> seriesId for every season (missing/unmigrated -> null).
// A SQLite read that hits the file while the boot-time schema upkeep is still
// writing to it fails with "database is locked". That is the cold start
// right after a deploy, and exactly when the first page load arrives.
function isBusyError(e) {
  return /locked|busy|SQLITE_BUSY|connection pool/i.test(String(e?.message || e));
}
function isMissingSchema(e) {
  return /no such (column|table)/i.test(String(e?.message || e));
}
async function readWithRetry(fn, attempts = 4) {
  let delay = 120;
  for (let i = 0; ; i++) {
    try {
      return await fn();
    } catch (e) {
      if (i >= attempts - 1 || !isBusyError(e)) throw e;
      await new Promise((r) => setTimeout(r, delay));
      delay *= 2;
    }
  }
}

// seasonId -> seriesId (null while unassigned). An EMPTY map means the column
// is not there yet (a database from before the series model, before the boot
// upkeep added it), and every caller then treats the seasons as belonging
// everywhere. It used to mean that for any error at all: a read that hit the
// file while the boot upkeep held it locked came back empty, and the seasons
// route answered with every season of every series until the next refresh.
// Now a busy file is retried, and any other failure is the caller's error.
export async function seasonSeriesMap(prisma) {
  try {
    const rows = await readWithRetry(() => prisma.$queryRawUnsafe(`SELECT "id", "seriesId" FROM "Season"`));
    return new Map(rows.map((r) => [r.id, r.seriesId || null]));
  } catch (e) {
    if (isMissingSchema(e)) return new Map();
    throw e;
  }
}

// Assign a season to a series (used by the admin season editor).
export async function setSeasonSeries(prisma, seasonId, seriesId) {
  await prisma.$executeRawUnsafe(`UPDATE "Season" SET "seriesId" = ? WHERE "id" = ?`, seriesId, seasonId);
  // The results archive files a season under its series: tell it.
  await refreshArchiveIndex(prisma);
}
