import type { Project, SurfaceKey } from '../types';
import { START_LIGHT_COLUMNS, startLightMesh } from '../core/gantry';

/**
 * The plain text side of an Assetto Corsa track. All of this the browser can
 * produce completely, no external tool involved.
 */

interface SurfaceDef {
  key: SurfaceKey;
  friction: number;
  wav: string;
  wavPitch: number;
  dirtAdditive: 0 | 1;
  isValidTrack: 0 | 1;
  blackFlagTime: number;
  sinHeight: number;
  sinLength: number;
  isPitlane: 0 | 1;
  vibrationGain: number;
  vibrationLength: number;
  damping: number;
}

const SURFACES: SurfaceDef[] = [
  {
    key: 'ROAD', friction: 0.98, wav: '', wavPitch: 0, dirtAdditive: 0, isValidTrack: 1,
    blackFlagTime: 0, sinHeight: 0, sinLength: 0, isPitlane: 0, vibrationGain: 0, vibrationLength: 0, damping: 0,
  },
  {
    key: 'KERB', friction: 0.94, wav: 'kerb.wav', wavPitch: 1.2, dirtAdditive: 0, isValidTrack: 1,
    blackFlagTime: 0, sinHeight: 0.01, sinLength: 0.6, isPitlane: 0, vibrationGain: 1, vibrationLength: 1.5, damping: 0,
  },
  {
    key: 'PIT', friction: 0.96, wav: '', wavPitch: 0, dirtAdditive: 0, isValidTrack: 1,
    blackFlagTime: 0, sinHeight: 0, sinLength: 0, isPitlane: 1, vibrationGain: 0, vibrationLength: 0, damping: 0,
  },
  {
    key: 'CONCRETE', friction: 0.92, wav: '', wavPitch: 0, dirtAdditive: 0, isValidTrack: 1,
    blackFlagTime: 0, sinHeight: 0, sinLength: 0, isPitlane: 0, vibrationGain: 0, vibrationLength: 0, damping: 0,
  },
  {
    key: 'GRASS', friction: 0.6, wav: 'grass.wav', wavPitch: 1, dirtAdditive: 1, isValidTrack: 0,
    blackFlagTime: 30, sinHeight: 0.02, sinLength: 0.5, isPitlane: 0, vibrationGain: 0.4, vibrationLength: 0.8, damping: 0.1,
  },
  {
    key: 'SAND', friction: 0.72, wav: 'sand.wav', wavPitch: 1, dirtAdditive: 1, isValidTrack: 0,
    blackFlagTime: 30, sinHeight: 0.02, sinLength: 0.4, isPitlane: 0, vibrationGain: 0.6, vibrationLength: 0.6, damping: 0.3,
  },
  /*
   * No WALL entry, deliberately, and it used to have one.
   *
   * surfaces.ini declares surfaces you DRIVE ON: the game finds the ground
   * under each tyre by casting straight down at meshes whose names carry
   * these keys. Declaring WALL moved every barrier out of AC's own built-in
   * wall handling and into that list -- and a ray cast downwards never meets
   * a vertical plane, so as far as the physics was concerned the barriers
   * simply were not there. Cars drove clean through every fence on the
   * circuit. WALL is AC's own namespace, handled as collision geometry
   * exactly because it is NOT declared -- no Kunos surfaces.ini declares it,
   * and the importer has known as much all along (see verify-import).
   */
];

export function surfacesIni(): string {
  const lines: string[] = [
    '; Generated by AC Track Editor.',
    '; A mesh is physical when its name, ignoring the first character, starts',
    '; with one of the KEY values below. That is why every road mesh is called',
    '; 1ROAD_..., every kerb 1KERB_... and so on.',
    '',
  ];
  SURFACES.forEach((s, i) => {
    lines.push(
      `[SURFACE_${i}]`,
      `KEY=${s.key}`,
      `FRICTION=${s.friction}`,
      `DAMPING=${s.damping}`,
      `WAV=${s.wav}`,
      `WAV_PITCH=${s.wavPitch}`,
      'FF_EFFECT=NULL',
      `DIRT_ADDITIVE=${s.dirtAdditive}`,
      `IS_VALID_TRACK=${s.isValidTrack}`,
      `BLACK_FLAG_TIME=${s.blackFlagTime}`,
      `SIN_HEIGHT=${s.sinHeight}`,
      `SIN_LENGTH=${s.sinLength}`,
      `IS_PITLANE=${s.isPitlane}`,
      `VIBRATION_GAIN=${s.vibrationGain}`,
      `VIBRATION_LENGTH=${s.vibrationLength}`,
      '',
    );
  });
  return lines.join('\r\n');
}

/**
 * `circuit` is not decoration. It is the tag Content Manager reads to decide
 * what a track can be used FOR: without it, starting an ordinary race throws
 * "track won't work with selected mode: tag 'circuit' is missing" before the
 * session will load. The other two say who made the thing; this one says what
 * the thing is, and every Kunos track carries it.
 *
 * It goes on a point to point course as well as a lap. The tag means "an
 * ordinary racing track", as against the `drift` and `drag` tags that pick the
 * other game modes -- a hillclimb is raced in exactly the mode a circuit is.
 */
const TRACK_TAGS = ['circuit', 'custom', 'ac-track-editor'];

export function uiTrackJson(p: Project, lengthMetres: number, widthMetres: number, pitboxes: number): string {
  const data = {
    name: p.meta.name,
    description: p.meta.description,
    tags: TRACK_TAGS,
    geotags: [],
    country: p.meta.country,
    city: p.meta.city,
    length: String(Math.round(lengthMetres)),
    width: String(Math.round(widthMetres)),
    pitboxes: String(pitboxes),
    run: p.meta.run,
    author: p.meta.author,
    version: p.meta.version,
    url: '',
  };
  return JSON.stringify(data, null, 2);
}

export interface MapParams {
  width: number;
  height: number;
  margin: number;
  scaleFactor: number;
  xOffset: number;
  zOffset: number;
  drawingSize: number;
}

/**
 * The section is `[PARAMETERS]`, spelled out. It was `[PARAMS]` here, which is
 * what the format is usually CALLED, and Assetto Corsa does not know that name:
 * it looks up the section by string, finds nothing, and falls back to defaults.
 * The map then draws with the wrong scale and the car marker sits nowhere near
 * the circuit. Checked against Kunos' own files -- magione, ks_barcelona,
 * ks_highlands all read `[PARAMETERS]`.
 */
export function mapIni(m: MapParams): string {
  return [
    '[PARAMETERS]',
    `WIDTH=${m.width}`,
    `HEIGHT=${m.height}`,
    `MARGIN=${m.margin}`,
    `SCALE_FACTOR=${m.scaleFactor}`,
    `X_OFFSET=${m.xOffset}`,
    `Z_OFFSET=${m.zOffset}`,
    `DRAWING_SIZE=${m.drawingSize}`,
    '',
  ].join('\r\n');
}

/** Optional, only written when the track really is a single kn5 file. */
export function modelsIni(slug: string): string {
  return ['[MODEL_0]', `FILE=${slug}.kn5`, 'POSITION=0,0,0', 'ROTATION=0,0,0', ''].join('\r\n');
}

/**
 * What each flag panel state is: the flag id that switches it on, the colour
 * it lights in, and how fast it blinks.
 *
 * The ids are Assetto Corsa's own, listed in `flag_colors.lut` in the patch's
 * config folder: 1 green, 2 yellow, 12 blue, 15 session suspended. 0 -- no
 * flag at all, which is what a practice session hands out -- is taken as green
 * so the panels sit in their resting state rather than glowing blank white.
 *
 * A blinking yellow is not decoration. It is how a real panel says "this is
 * new" rather than "this is still on", and it is the one state a driver has to
 * pick up out of the corner of their eye at 250 km/h. Blue blinks for the same
 * reason. Green and red are steady, because they mean a condition rather than
 * an event.
 */
const FLAG_STATES = [
  { name: 'GREEN', ids: [0, 1], colour: '30, 220, 70', flashing: 0 },
  { name: 'YELLOW', ids: [2], colour: '255, 210, 30', flashing: 3 },
  { name: 'BLUE', ids: [12], colour: '40, 110, 255', flashing: 3 },
  { name: 'RED', ids: [15], colour: '255, 40, 30', flashing: 0 },
] as const;

/** Assetto Corsa reads its ini files as Windows text, so every line ends. */
const CRLF = '\r\n';

/** The highest flag id worth writing out. Above this AC has nothing to say. */
const FLAG_ID_MAX = 16;

/**
 * A condition's lookup table: 1 at the ids that switch it on, 0 everywhere.
 *
 * Every id is written out rather than only the interesting ones. A LUT
 * INTERPOLATES between the points it is given, so a table holding just the one
 * entry that matters reads as that value everywhere, and the panel shows
 * yellow for a green flag.
 */
function flagLut(ids: readonly number[]): string {
  const points: string[] = [];
  for (let i = 0; i <= FLAG_ID_MAX; i++) points.push(`${i}=${ids.includes(i) ? 1 : 0}`);
  return `LUT=(|${points.join('|')}|)`;
}

/* ------------------------------------------------------------------ */
/* The start lights                                                    */
/* ------------------------------------------------------------------ */

/**
 * The start gantry's lamps.
 *
 * This one cannot be done with conditions, and it took a working version to
 * see why. A track config's conditions read the time, the sun, the weather and
 * the FLAG, and that is the whole list -- so the best a config can say is "red
 * whenever no flag is showing". Which is right for the last few seconds before
 * a race and wrong for everything else: it also means red through the whole of
 * every practice session, and red through the entire wait on the grid, with
 * all five lamps on at once the whole time. Real start lights are dark until
 * the countdown and then come on ONE AT A TIME.
 *
 * A track script can see the countdown itself. `sim.timeToSessionStart` is the
 * milliseconds left before the green, which is exactly the number the sequence
 * is made of, and CSP has run Lua out of a track folder for years -- the SDK
 * ships definitions for it under `ac_track_script`, scoped to `content/tracks`
 * (see extension/internal/lua-sdk/rules.json in any patched install), and it is
 * loaded by a [SCRIPT_...] section in this very file.
 *
 * So the lamps are driven from Lua and there is no MATERIAL_ADJUSTMENT for
 * them at all. Two things writing the same three material properties every
 * frame is a race nobody wins.
 */
function startLightLines(): string[] {
  return [
    '',
    '; The five lights over the line, counted down by extension/start_lights.lua.',
    '[SCRIPT_...]',
    'ACTIVE = 1',
    `SCRIPT = ${START_LIGHTS_LUA}`,
  ];
}

/** Written next to ext_config.ini, which is where SCRIPT= looks for it. */
export const START_LIGHTS_LUA = 'start_lights.lua';

/**
 * The track script itself.
 *
 * Short on purpose. It runs every frame of every session on the circuit, so
 * the only thing it does per frame is work out a number from 0 to 5 and
 * compare it with the one it set last time.
 */
export function startLightsLua(): string {
  const columns = START_LIGHT_COLUMNS;
  return [
    '-- The start lights over the timing line. Written by AC Track Editor.',
    '--',
    '-- The gantry carries five columns of lamps as five separate meshes, which',
    '-- is the whole reason they are separate: they have to come on one at a',
    '-- time. See core/gantry.ts in the editor, which names them.',
    '',
    `local COLUMNS = ${columns}`,
    'local columns = {}',
    'for i = 1, COLUMNS do',
    '  -- ensureUniqueMaterials is not optional. A scene reference shares its',
    '  -- material with the rest of the scene until it is told not to, and all',
    '  -- five columns are one material in the model -- so without this, lighting',
    '  -- the first lamp lights all five and the sequence cannot be seen.',
    `  columns[i] = ac.findMeshes('${startLightMesh(1).replace(/1$/, '')}' .. i):ensureUniqueMaterials()`,
    'end',
    '',
    '-- Lit is exactly what the model bakes (EMISSIVE_MATERIAL_PROPS in the',
    "-- editor's kn5 writer); out is every term at zero, which is black glass.",
    '-- ksAmbient is the one that does the work: it is what draws a texture at',
    '-- its own brightness whatever the sun is doing.',
    'local function set(mesh, on)',
    "  mesh:setMaterialProperty('ksAmbient', on and 1.3 or 0)",
    "  mesh:setMaterialProperty('ksDiffuse', on and 0.12 or 0)",
    "  mesh:setMaterialProperty('ksEmissive', on and 1 or 0)",
    'end',
    '',
    'local shown = -1',
    'local function show(n)',
    '  if n == shown then return end',
    '  shown = n',
    '  for i = 1, COLUMNS do set(columns[i], i <= n) end',
    'end',
    '',
    '-- Dark on arrival, so a track standing empty is not lit up.',
    'show(0)',
    '',
    'function script.update(dt)',
    '  local sim = ac.getSim()',
    '  local lit = 0',
    '  if sim.raceSessionType == ac.SessionType.Race and not sim.isSessionStarted then',
    '    local left = sim.timeToSessionStart',
    '    -- -1 means the game has no countdown to report.',
    '    if left >= 0 and left < COLUMNS * 1000 then',
    '      -- One a second, so the fifth comes on with a second still to run and',
    '      -- they all go out together when the count reaches zero. Five is the',
    '      -- point: it is the number you can read at a glance from the grid.',
    '      lit = COLUMNS - math.floor(left / 1000)',
    '    end',
    '  end',
    '  show(math.max(0, math.min(COLUMNS, lit)))',
    'end',
    '',
  ].join('\r\n');
}

/**
 * The Custom Shaders Patch config that makes the flag panels follow the race.
 *
 * Written with the track whenever the barrier carries panels. None of the
 * machinery is invented here -- it is what the patch's own track configs do,
 * and the shape is lifted from two of them:
 *
 *   - A condition per state, INPUT=FLAG_TYPE through a lookup table, with
 *     FLASHING_FREQUENCY on the ones that blink. That is abu_dhabi_2021_chq's
 *     RACING_FLAG_YELLOW / _BLUE / _GREEN, and it is what makes a yellow
 *     actually flash rather than sit there.
 *   - A MATERIAL_ADJUSTMENT per state on the SAME material, each falling back
 *     to ORIGINAL when its own flag is not the one showing. Only one flag is
 *     ever up, so exactly one of them is driving the screen at a time.
 *   - One LIGHT_SERIES off the patch's own RACING_FLAG, which outputs the flag
 *     COLOUR rather than a switch, so the light the panels throw on the barrier
 *     after dark is the colour they are showing. CLUSTER_THRESHOLD is what
 *     keeps a lap's worth of them affordable.
 *
 * `common/conditions.ini` ships with the patch and is where RACING_FLAG comes
 * from; the four conditions below are ours, numbered high to stay clear of it.
 *
 * The material name is the editor's own key, because that is what the kn5
 * writer puts in the material table (see buildExport).
 */
export function extConfigIni(has: { flagPanels: boolean; startLights: boolean }): string {
  const lines: string[] = [
    '; Track wiring for Custom Shaders Patch, written by AC Track Editor.',
    '; Without CSP everything below is simply lit as it was modelled.',
    '',
    '[INCLUDE]',
    'INCLUDE = common/conditions.ini',
  ];

  if (has.startLights) lines.push(...startLightLines());
  if (!has.flagPanels) return lines.join(CRLF) + CRLF;

  FLAG_STATES.forEach((state, i) => {
    lines.push(
      '',
      `[CONDITION_${900 + i}]`,
      `NAME=FLAG_PANEL_${state.name}`,
      'INPUT=FLAG_TYPE',
      flagLut(state.ids),
      // Held for a moment and switched without delay: a flag that flickers
      // through a state on its way to another one is worse than no panel.
      'INPUT_STAY_FOR=1.0',
      'INPUT_CHANGE_DELAY=0',
    );
    if (state.flashing > 0) {
      lines.push(`FLASHING_FREQUENCY=${state.flashing}`, 'FLASHING_SMOOTHNESS=0.15', 'FLASHING_SYNCED=1');
    }
  });

  FLAG_STATES.forEach((state, i) => {
    lines.push(
      '',
      `[MATERIAL_ADJUSTMENT_${900 + i}]`,
      'ACTIVE = 1',
      `DESCRIPTION = flag panels, ${state.name.toLowerCase()}`,
      'MATERIALS = led_flag',
      'KEY_0 = ksEmissive',
      `VALUE_0 = ${state.colour}, 0.01`,
      'VALUE_OFF_0 = ORIGINAL',
      'KEY_1 = ksDiffuse',
      'VALUE_1 = 0',
      'VALUE_OFF_1 = ORIGINAL',
      `CONDITION = FLAG_PANEL_${state.name}`,
    );
  });

  lines.push(
    '',
    '[LIGHT_SERIES_900]',
    'ACTIVE = 1',
    'DESCRIPTION = the light the panels throw',
    'MATERIALS = led_flag',
    'OFFSET = 0,0,0',
    'DIRECTION = NORMAL',
    'SPOT = 150',
    'SPOT_SHARPNESS = 0.2',
    'RANGE = 6',
    'RANGE_GRADIENT_OFFSET = 0.2',
    'FADE_AT = 1000',
    'FADE_SMOOTH = 66',
    'DIFFUSE_CONCENTRATION = 0.5',
    'CLUSTER_THRESHOLD = 10',
    'COLOR = 255,255,255,0.01',
    'CONDITION = RACING_FLAG',
    '',
  );

  return lines.join('\r\n');
}
